// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string `json:"id"`
	CommentID int32  `json:"comment_id"`
	Up        int32  `json:"up"`
	Down      int32  `json:"down"`
	Content   string `json:"content"`
	ItemID    int32  `json:"item_id"`
	Thumb     string `json:"thumb"`
}

type Item struct {
	ID         string   `json:"id"`
	ItemID     int32    `json:"item_id"`
	Title      string   `json:"title"`
	Artist     string   `json:"artist"`
	Album      string   `json:"album"`
	URL        string   `json:"url"`
	AcrID      *string  `json:"acr_id,omitempty"`
	Provider   string   `json:"provider"`
	SpotifyURL *string  `json:"spotify_url,omitempty"`
	SpotifyID  *string  `json:"spotify_id,omitempty"`
	YoutubeURL *string  `json:"youtube_url,omitempty"`
	YoutubeID  *string  `json:"youtube_id,omitempty"`
	Comment    *Comment `json:"comment,omitempty"`
}

type Query struct {
}
