name: Build and Publish
on:
  push:
    branches: ['main']
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'
      - uses: actions/checkout@v3
      - uses: ko-build/setup-ko@v0.6
      - env:
          KO_DOCKER_REPO: ghcr.io/pacerino/pr0sauce_graphql
        run: ko build
